
apiVersion: v1
kind: Service
metadata:
  name: daytrader3ee6
  labels:
    app: daytrader3ee6
spec:
  ports:
    - port: 9080
  selector:
    app: daytrader3ee6
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: daytrader3ee6
  name: daytrader3ee6
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: daytrader3ee6
    spec:
      containers:
      - image: mycluster.icp:8500/default/daytrader3ee6:latest
        name: daytrader3ee6
        ports:
        - containerPort: 9080
          protocol: TCP
